site_name: Programaci칩 web
site_url: https://gss-mtig.github.io/web-mgeo/
site_description: Programaci칩 web
site_author: web-mgeo
theme:
  name: 'material'
  language: 'es'
  highlightjs: true

markdown_extensions:
  - codehilite:
      linenums: True
  - admonition
  - pymdownx.magiclink
  - pymdownx.superfences
  - footnotes
repo_url: "https://github.com/gss-mtig/web-mgeo"

nav:
- Home: index.md
- Introducci칩n al desarrollo Web: introduccion_web.md
- HTML: html.md
- Elementos HTML: elementos_html.md
- CSS: css.md
- CSS el modelo de caja: css_bbox.md
- CSS dise침o: css_diseno.md
- JS: js.md

plugins:
    - search
